# Generated by Django 4.2.5 on 2023-10-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_description_alter_bid_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
