# Generated by Django 4.2.5 on 2023-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
